# Production Cache Configuration
# Üretim ortamında dağıtık önbellek için Redis kullanıyoruz.
spring.cache.type=redis

# Üretim Redis Sunucusu Bağlantı Bilgileri (Çevre değişkenleri ile ezilebilir)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
